import java.util.Scanner;

public class Guess_tn {
    public static void main(String[] args) {

// The setup: A number is randomly generated by a computer within a specific range (e.g., 1 to 100). The player does not know this number.
//The guess: The player enters a guess.
//The feedback: The computer tells the player if their guess was too high, too low, or correct.
//The goal: The player continues to guess, using the feedback to narrow down the possibilities.
//Winning or losing: The game ends when the player guesses the number correctly or when they run out of attempts.
//Scoring: The number of attempts it takes to guess the number can be used as a score.
        // Let's go with the player guesses the number correctly
        Scanner pd = new Scanner(System.in);
        int a = 27;// Comp input
        System.out.println("nuv em anukunavoo adhi enter chey :");
        int attempt =0;

        while(true){
            int n = pd.nextInt();
            if (a == n) {
                System.out.println("Correct raa ...");
                attempt++;
                System.out.println("Score: ");
                System.out.println(attempt);

                break;

            }
            if (n < a) {

                System.out.println("Number inka pedhadhi");
                attempt++;
            }
            if (n > a) {
                System.out.println("Number inka chinnadhi");
                attempt++;
            }
        }
    }
}


